### ISSUE TITLE
Телепорт по камерам

### ISSUE THREAD

**Issue by bigenergy** [Dseym/amongUsMinecraft#10]
Когда просматриваешь камеры, если нажать выйти то перса телепортирует в место куда смотрит камера.

**Comment by bigenergy** [comment]
+ когда камеры смотришь, персонаж получается неуязвим

**Comment by bigenergy** [comment]
И если уже кто-то есть на камере, присоединиться к камере и выйти, после выхода с камер будет видно кто остался на камере 
![image](https://user-images.githubusercontent.com/17977139/96356535-8852e580-10f8-11eb-97c2-44510d6dc7cf.png)

**Comment by Dseym** [comment]
Хорошо, все исправлю

**Comment by Dseym** [comment]
Это проблема клиента, я не смогу ничего сделать с этим. Если Вам нужно знать подробности, почему я не могу это исправить, пишите.

**Comment by Dseym** [comment]
Игрок всегда уязвим на камерах, но не всегда отображается
