### ISSUE TITLE
Players arena fix please and Imposter count error??

### ISSUE THREAD

**Issue by LeePC** [Dseym/amongUsMinecraft#11]
map: The Skeld
visual_task: true
confirm_eject: true
imposters: 1
emergency_metting: 1
timeout_metting: 16
time_voting: 60
speed_player: 2
timeout_kill: 15
distance_kill: 2
playerOnCount: 3
tasksNum: 16
spawns:
- 0.5, 98, 3.5
- 1.5, 98, 3.5
- 2.5, 98, 2.5
- 3.5, 98, 1.5
- 3.5, 98, 0.5
- 3.5, 98, -0.5
- 2.5, 98, -1.5
- 1.5, 98, -2.5
- 0.5, 98, -2.5
- -0.5, 98, -2.5
- -1.5, 98, -1.5
- -2.5, 98, -0.5
- -2.5, 98, 0.5
- -2.5, 98, 1.5
- -1.5, 98, 2.5
- -0.5, 98, 3.5

16 players.....

![2020-10-26_06 04 36](https://user-images.githubusercontent.com/8704225/97119096-4dccf680-1751-11eb-9d2e-9a8f85cf9915.png)

![2020-10-26_08 59 19](https://user-images.githubusercontent.com/8704225/97122492-8b3d7e00-1769-11eb-8987-d7f7034d18d8.png)

Play Error Fix Please

[latest.log](https://github.com/Dseym/amongUsMinecraft/files/5436197/latest.log)

**Comment by Dseym** [comment]
Perhaps you have a default config in your lobby. I will now make the default lobby settings for each lobby and post the update, wait. Everything will be fixed as well.

**Comment by Dseym** [comment]
Added the defaultConfig setting for the lobby in config.yml
