### ISSUE TITLE
error fix please

### ISSUE THREAD

**Issue by LeePC** [Dseym/amongUsMinecraft#12]
[latest.log](https://github.com/Dseym/amongUsMinecraft/files/5471960/latest.log)

and option fix please

map: The Skeld
visual_task: true
confirm_eject: true
imposters: 1
emergency_metting: 1
timeout_metting: 10
time_voting: 60
speed_player: 2
timeout_kill: 15
distance_kill: 2
playerOnCount: 3
tasksNum: 16
spawns:
- 0.5, 98, 3.5
- 1.5, 98, 3.5
- 2.5, 98, 2.5
- 3.5, 98, 1.5
- 3.5, 98, 0.5
- 3.5, 98, -0.5
- 2.5, 98, -1.5
- 1.5, 98, -2.5
- 0.5, 98, -2.5
- -0.5, 98, -2.5
- -1.5, 98, -1.5
- -2.5, 98, -0.5
- -2.5, 98, 0.5
- -2.5, 98, 1.5
- -1.5, 98, 2.5
- -0.5, 98, 3.5

**Comment by Dseym** [comment]
fixed
