### ISSUE TITLE
not game translate.....

### ISSUE THREAD

**Issue by LeePC** [Dseym/amongUsMinecraft#3]
notPerm: "권한이 없습니다"
lacksArgs: "인자가 부족합니다"
success: "성공적으로 완료되었습니다"
plNotInLobby: "로비에 없습니다"
plInLobby: "이미 로비에 있습니다"
lobbyNotFound: "로비를 찾을수 없습니다"
notGame: "게임없음"
isGameStart: "게임이 진행중입니다"
notFoundSett: "설정을 찾을수 없습니다"
incorrectValue: "잘못된 값"
senderNotPl: "당신은 참가자가 아닙니다"
notFoundConfig: "그러한 설정 파일이 없습니다."
helpMenu: "\n------------명령어------------\n /among create gameConf - §e게임을 만들다§r\n /among start - §e게임을 시작하다§r\n /among v (nickName/skip) - §e투표§r\n /among help - §e이 메뉴§r\n /among vopen - §e오픈 투표 태블릿§r\n /among setting sett val - §e게임 설정 변경§r\n /among join name - §e로비에 들어가다§r\n /among leave - §e로비에서 나가다§r\n /among setlobby name - §e로비 만들기§r\n /among list - §e로비 목록§r\n ------------명령어------------"

visibleBody: "근처에서 시체 발견"
sabotageLimit: "여러 번의 방해 행위는 허용되지 않습니다."

not game translate ......
fix please

**Comment by Dseym** [comment]
Oops, we'll fix everything now.

**Comment by Dseym** [comment]
Fixed
