### ISSUE TITLE
Проблема со стойками.

### ISSUE THREAD

**Issue by UnDef1nedd** [Dseym/amongUsMinecraft#5]
Я тестирую плагин на своём сервере, и вместо снежков вижу подсвечиваемые стойки. Я полагаю, это из-за какого-то плагина, так как ядро я брал по ссылке в РэдМи плагина, плагин тоже, да и я сам тестировал на версии 1.12.2. Подскажите, какой из плагинов мешает или прошу сделать совместимость. Скриншоты прикреплены. Спасибо.
![1-1](https://user-images.githubusercontent.com/57291641/96166929-53436900-0f27-11eb-866e-04ab1d1396c3.png)
![1-2](https://user-images.githubusercontent.com/57291641/96166946-58a0b380-0f27-11eb-945d-f297c000bfe4.png)

**Comment by Dseym** [comment]
Армор стенды уже были на карте, их можно просто убрать командой /kill

**Comment by UnDef1nedd** [comment]
Я так и сделал, но теперь показываются не все снежки. Например, оказывается, было задание, которое никак не подсвечивалось. Скриншот приложен.

 + Снежки не перестают светится после выполнения задания.
![1](https://user-images.githubusercontent.com/57291641/96239789-cfca5c00-0fa8-11eb-9aef-ead99c34e4a2.png)

**Comment by Dseym** [comment]
Возможно во время начала игры - территория была выгружена. Попробуйте разместить лобби поближе к самой карте

**Comment by UnDef1nedd** [comment]
Лобби и так очень близко к карте. Там получилось так: Некий макет корабля (в котором расположено лобби), под ним один слой дёрна (я не знаю, косяк ли это с генерацией или так надо), и сразу же идёт корабль под всем этим. Так что всё близко, там расстояние в плане высоты +- 3 блока.

**Comment by Dseym** [comment]
Странно, все должно работать. Попробуйте отключить анти чит

**Comment by UnDef1nedd** [comment]
Заработало, всё отлично. Благодарю!
