### ISSUE TITLE
Дублирование действий плагином. (Чат и Саботажи) + Дополнительно

### ISSUE THREAD

**Issue by UnDef1nedd** [Dseym/amongUsMinecraft#6]
Я тестирую плагин на своём сервере и вместо одного игрок отправляет 2 сообщения в чат. А должно быть, по идее, одно. Скриншот прикрепил.

+ Можно писать в чат ВНЕ собрания.
+ Баг с 2-мя разами работает не только с чатом. Почти все действия воспринимаются плагином как 2 раза сделанные. Вот, например, я нажал на саботаж, я нажал один раз, но плагин и сделал саботаж, и сказал, что можно устраивать только один. Скриншота прикрепил. 

Спасибо.
![2-1](https://user-images.githubusercontent.com/57291641/96168461-73742780-0f29-11eb-922a-0e26960f5359.png)
![2-2](https://user-images.githubusercontent.com/57291641/96168477-77a04500-0f29-11eb-8dfa-fb2d824db16a.png)
![2-3](https://user-images.githubusercontent.com/57291641/96168485-7a9b3580-0f29-11eb-9f0a-40958976502e.png)

**Comment by Dseym** [comment]
Хорошо, Вы не первый кто сообщил об этой проблеме, посмотрю - исправлю

**Comment by UnDef1nedd** [comment]
Спасибо.

**Comment by Dseym** [comment]
Все исправлено, спасибо за баг-репорт!
