### ISSUE TITLE
Проблема с автоматическим стартом игры.

### ISSUE THREAD

**Issue by UnDef1nedd** [Dseym/amongUsMinecraft#7]
Я тестирую плагин на своём сервере. И у меня проблема с автозапуском, игроков достаточно, а обратный отсчёт не пошёл. Если это так задумано, то рекомендую в конфиг добавить возможность регулировать вкл/выкл автозапуска, кол-во игроков для начала отсчёта и время на запуск. Скриншот прикрепил.

Спасибо.
![3-1](https://user-images.githubusercontent.com/57291641/96169714-432d8880-0f2b-11eb-86de-d442b36eafdc.png)

**Comment by Dseym** [comment]
Автозапуск работает когда все 10 игроков в лобби. Если надо добавить в конфиг - тогда добавлю

**Comment by UnDef1nedd** [comment]
Спасибо.
