### ISSUE TITLE
Sign Join System Add Please

### ISSUE THREAD

**Issue by LeePC** [Dseym/amongUsMinecraft#9]
Line : [Among]
Line2 : ArenaName

Add Please

And Map Add Tutorial Please

**Comment by Dseym** [comment]
Line: [Among] Line2: ArenaName Should this be added to the Scoreboard?
Ok, the tutorial will be added in the next update.

**Comment by LeePC** [comment]
> Line: [Among] Line2: ArenaName Should this be added to the Scoreboard?
> Ok, the tutorial will be added in the next update.

Scoreboard No
Sign Yes

**Comment by Dseym** [comment]
Okey

**Comment by Dseym** [comment]
Do you need a tutorial on how to add your custom map to the plugin? Did I understand correctly?

**Comment by LeePC** [comment]
yes

**Comment by Dseym** [comment]
okey

**Comment by Dseym** [comment]
Added mapConfig
